[versions]
agp = "8.4.0"
android-compileSdk = "34"
android-minSdk = "26"
android-targetSdk = "34"
androidx-activity-compose = "1.9.0"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.13.1"
androidx-espresso-core = "3.5.1"
androidx-material = "1.12.0"
androidx-test-junit = "1.1.5"
compose-plugin = "1.6.10"
faceDetection = "16.1.6"
junit = "4.13.2"
kotlin = "2.0.0"
kotlinx-coroutines = "1.8.1"
kotlinx-io = "0.4.0"
kotlinx-datetime = "0.6.0"
kotlinx-serialization = "1.7.0"
bouncy-castle = "1.78.1"
tink = "1.13.0"
jetbrainsKotlinJvm = "2.0.0"
ksp = "2.0.0-1.0.22"
androidx-biometrics = "1.2.0-alpha05"
volley = "1.2.1"
cbor = "0.9"
scuba = "0.0.26"
jmrtd = "0.7.42"
mlkit = "16.0.0"
camera = "1.3.3"
compose-material3 = "1.2.1"
compose-material-icons-extended = "1.6.7"
androidx-navigation = "2.7.7"
code-scanner = "2.1.0"
ktor = "2.3.10"
javax-servlet-api = "4.0.1"
androidx-lifecycle = "2.2.0"
androidx-lifecycle-ktx = "2.8.2"
compose-runtime-livedata = "1.6.8"
accompanist-permissions = "0.34.0"
work-version = "2.9.0"
play-services-base = "18.2.0"
play-services-basement = "18.2.0"
play-services-tasks = "18.0.2"
nimbus-sdk = "11.8"
zxing = "3.5.3"
gretty = "4.1.4"
hsqldb = "2.7.2"
mysql = "8.0.16"
compose-junit4 = "1.6.8"
compose-test-manifest = "1.6.8"
androidx-fragment = "1.8.0"
navigation-plugin = "2.7.7"
androidx-preference = "1.2.1"
exif = "1.3.7"
ausweis-sdk = "2.1.1"
jetbrains-navigation = "2.7.0-alpha07"
cameraLifecycle = "1.3.4"
buildconfig = "5.3.5"

[libraries]
face-detection = { module = "com.google.mlkit:face-detection", version.ref = "faceDetection" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref="kotlinx-coroutines" }
kotlinx-coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref="kotlinx-coroutines" }
kotlinx-io-bytestring = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-bytestring", version.ref = "kotlinx-io"}
kotlinx-io-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io"}
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
bouncy-castle-bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncy-castle" }
bouncy-castle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncy-castle" }
tink = { group = "com.google.crypto.tink", name = "tink-android", version.ref = "tink"}
ksp-symbol-processing-api = {module="com.google.devtools.ksp:symbol-processing-api", version.ref="ksp"}
androidx-biometrics = { module = "androidx.biometric:biometric", version.ref = "androidx-biometrics" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
cbor = { module = "co.nstant.in:cbor", version.ref = "cbor" }
net-sf-scuba-scuba-sc-android = { group = "net.sf.scuba", name = "scuba-sc-android", version.ref="scuba" }
org-jmrtd-jmrtd = { group = "org.jmrtd", name ="jmrtd", version.ref="jmrtd" }
com-google-mlkit-text-recognition = { group = "com.google.mlkit", name = "text-recognition", version.ref="mlkit" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-material-icons-extended" }
androidx-navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "androidx-navigation" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
code-scanner = { module = " com.budiyev.android:code-scanner", version.ref = "code-scanner" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
javax-servlet-api = { module = "javax.servlet:javax.servlet-api", version.ref = "javax-servlet-api" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle-ktx" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-ktx" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose-runtime-livedata" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist-permissions"}
androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "work-version"}
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "play-services-base" }
play-services-basement = { module = "com.google.android.gms:play-services-basement", version.ref = "play-services-basement" }
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "play-services-tasks" }
nimbus-oauth2-oidc-sdk = { module = "com.nimbusds:oauth2-oidc-sdk", version.ref = "nimbus-sdk" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }
hsqldb = { module = "org.hsqldb:hsqldb", version.ref = "hsqldb" }
mysql = { module = "mysql:mysql-connector-java", version.ref = "mysql" }
compose-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref="compose-junit4" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref="compose-test-manifest" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exif" }
ausweis-sdk = { module = "com.governikus:ausweisapp", version.ref = "ausweis-sdk"}
jetbrains-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref="jetbrains-navigation" }
jetbrains-navigation-runtime = { module = "org.jetbrains.androidx.navigation:navigation-runtime", version.ref="jetbrains-navigation" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }

[bundles]
google-play-services = ["play-services-base", "play-services-basement", "play-services-tasks"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gretty = { id = "org.gretty", version.ref = "gretty"}
navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation-plugin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
parcelable = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
